[theme]
base="light"

# Cor primária azul
primaryColor="#1E88E5"

# Cor de fundo branca
backgroundColor="#FCFCF9"

# Fundo secundário (sidebar) azul claro
secondaryBackgroundColor="#F3F3EE"

# Cor do texto (escura)
textColor="#13343B"

# Fonte
font="sans serif"