[theme]
base="light"

# Cor primária azul
primaryColor="#1E88E5"

# Cor de fundo branca
backgroundColor="#FFFFFF"

# Fundo secundário (sidebar) azul claro
secondaryBackgroundColor="#F0F8FF"

# Cor do texto (escura)
textColor="#333333"

# Fonte
font="sans-serif"